import type { WorkCategory, WorkMode } from "../../domain/src/models";
import type { SimulationPersona, WeightedValue } from "./types";

const ALL_WORK_DAYS = [1, 2, 3, 4, 5] as const;

function categories(entries: Array<[WorkCategory, number]>): WeightedValue<WorkCategory>[] {
  return entries.map(([value, weight]) => ({ value, weight }));
}

function modes(entries: Array<[WorkMode, number]>): WeightedValue<WorkMode>[] {
  return entries.map(([value, weight]) => ({ value, weight }));
}

function context(family: string, appName: string, ...syntheticTitles: string[]) {
  return { family, appName, syntheticTitles };
}

export const PERSONA_CATALOG: SimulationPersona[] = [
  {
    schemaVersion: 1,
    id: "data-analyst",
    version: "1.0.0",
    role: "Data Analyst",
    displayName: "Senior Data Analyst",
    responsibilities: [
      "Translate business questions into defensible analysis",
      "Maintain recurring executive and operating reports",
      "Build and migrate decision-support dashboards",
      "Validate data quality and explain metric discrepancies",
      "Respond to time-sensitive stakeholder requests",
    ],
    projects: ["Dashboard migration", "Quarter-end reporting", "Experiment analysis", "Metrics quality review"],
    appContexts: [
      context("data", "DataGrip", "SIMULATED — warehouse query", "SIMULATED — dashboard migration model"),
      context("spreadsheet", "Microsoft Excel", "SIMULATED — quarter-end workbook", "SIMULATED — metric validation"),
      context("bi", "Tableau", "SIMULATED — operating dashboard", "SIMULATED — migration QA"),
      context("chat", "Slack Sandbox", "SIMULATED — analytics requests", "SIMULATED — reporting coordination"),
      context("documents", "Notion Sandbox", "SIMULATED — analysis brief", "SIMULATED — metric definitions"),
    ],
    categoryWeights: categories([
      ["Planned analysis / project work", 18], ["Ad hoc stakeholder requests", 10], ["Recurring reporting", 14],
      ["Dashboard development / edits", 14], ["SQL / data modeling / query work", 20], ["QA / data validation", 7],
      ["Debugging / issue investigation", 4], ["Documentation / requirement clarification", 3],
      ["Meetings / stakeholder syncs", 7], ["Admin / coordination", 2], ["Blocked / waiting / dependency delay", 1],
    ]),
    modeWeights: modes([["Deep work", 44], ["Reactive", 18], ["Collaborative", 12], ["Fragmented", 20], ["Blocked", 6]]),
    meetingBehavior: { weeklyMinutes: { min: 300, typical: 420, max: 660 }, recurringMeetings: ["Analytics planning", "Stakeholder readout", "Metric review"], doubleBookingPercent: 2 },
    deepWorkCadence: { preferredDays: [2, 3, 4], preferredStartHours: [9, 10, 13], blockMinutes: { min: 45, typical: 105, max: 180 } },
    reactiveLoad: { typicalPercent: 16, burstsPerDay: { min: 1, typical: 3, max: 7 }, incidentWeekPercent: 12 },
    interruptions: { perFocusHour: 0.75, recoveryMinutes: { min: 5, typical: 14, max: 30 }, sources: ["chat", "email", "meeting"] },
    stakeholders: ["Product", "Finance", "Operations", "Data Platform"],
    typicalWorkday: { start: "09:00", end: "17:30", workDays: [...ALL_WORK_DAYS] },
    seasonalPressures: ["Quarter-end reporting ramps for three weeks", "Dashboard launches create short QA and reactive spikes"],
  },
  {
    schemaVersion: 1, id: "software-engineer", version: "1.0.0", role: "Software Engineer", displayName: "Senior Software Engineer",
    responsibilities: ["Deliver product changes", "Review and integrate code", "Investigate defects and incidents", "Maintain automated quality checks", "Document technical decisions"],
    projects: ["Workflow reliability", "Platform modernization", "Customer-facing feature", "Operational tooling"],
    appContexts: [
      context("code", "Visual Studio Code", "SIMULATED — feature implementation", "SIMULATED — incident repair"),
      context("terminal", "Terminal", "SIMULATED — local build", "SIMULATED — focused verification"),
      context("version-control", "GitHub Sandbox", "SIMULATED — pull request review", "SIMULATED — release branch"),
      context("project", "Linear Sandbox", "SIMULATED — sprint issue", "SIMULATED — defect triage"),
      context("chat", "Slack Sandbox", "SIMULATED — engineering coordination", "SIMULATED — incident channel"),
    ],
    categoryWeights: categories([
      ["Planned analysis / project work", 32], ["Ad hoc stakeholder requests", 10], ["Recurring reporting", 3],
      ["SQL / data modeling / query work", 3], ["QA / data validation", 12], ["Debugging / issue investigation", 18],
      ["Documentation / requirement clarification", 8], ["Meetings / stakeholder syncs", 9], ["Admin / coordination", 3],
      ["Blocked / waiting / dependency delay", 2],
    ]),
    modeWeights: modes([["Deep work", 52], ["Reactive", 17], ["Collaborative", 11], ["Fragmented", 15], ["Blocked", 5]]),
    meetingBehavior: { weeklyMinutes: { min: 240, typical: 360, max: 540 }, recurringMeetings: ["Engineering planning", "Design review", "Retrospective"], doubleBookingPercent: 1 },
    deepWorkCadence: { preferredDays: [1, 2, 4], preferredStartHours: [9, 10, 14], blockMinutes: { min: 60, typical: 120, max: 210 } },
    reactiveLoad: { typicalPercent: 15, burstsPerDay: { min: 1, typical: 2, max: 6 }, incidentWeekPercent: 14 },
    interruptions: { perFocusHour: 0.55, recoveryMinutes: { min: 7, typical: 16, max: 35 }, sources: ["chat", "alert", "meeting"] },
    stakeholders: ["Product", "Design", "Customer Support", "Platform Engineering"],
    typicalWorkday: { start: "09:30", end: "18:00", workDays: [...ALL_WORK_DAYS] },
    seasonalPressures: ["Launch weeks increase QA and coordination", "Incidents create sharp reactive spikes followed by recovery"],
  },
  {
    schemaVersion: 1, id: "product-manager", version: "1.0.0", role: "Product Manager", displayName: "Senior Product Manager",
    responsibilities: ["Define product priorities", "Clarify requirements and tradeoffs", "Coordinate cross-functional delivery", "Synthesize customer evidence", "Communicate launch readiness"],
    projects: ["Quarterly roadmap", "Product launch", "Customer discovery", "Workflow adoption"],
    appContexts: [
      context("project", "Linear Sandbox", "SIMULATED — roadmap planning", "SIMULATED — launch scope"),
      context("documents", "Notion Sandbox", "SIMULATED — product requirements", "SIMULATED — discovery synthesis"),
      context("design", "Figma", "SIMULATED — product review", "SIMULATED — prototype feedback"),
      context("chat", "Slack Sandbox", "SIMULATED — cross-functional coordination", "SIMULATED — launch channel"),
      context("meetings", "Zoom Sandbox", "SIMULATED — stakeholder review", "SIMULATED — customer interview"),
    ],
    categoryWeights: categories([
      ["Planned analysis / project work", 18], ["Ad hoc stakeholder requests", 12], ["Recurring reporting", 4],
      ["Dashboard development / edits", 3], ["QA / data validation", 5], ["Debugging / issue investigation", 3],
      ["Documentation / requirement clarification", 22], ["Meetings / stakeholder syncs", 24], ["Admin / coordination", 7],
      ["Blocked / waiting / dependency delay", 2],
    ]),
    modeWeights: modes([["Deep work", 24], ["Reactive", 18], ["Collaborative", 38], ["Fragmented", 17], ["Blocked", 3]]),
    meetingBehavior: { weeklyMinutes: { min: 600, typical: 900, max: 1260 }, recurringMeetings: ["Product triad", "Delivery review", "Customer discovery", "Roadmap review"], doubleBookingPercent: 5 },
    deepWorkCadence: { preferredDays: [1, 5], preferredStartHours: [8, 9, 14], blockMinutes: { min: 40, typical: 75, max: 135 } },
    reactiveLoad: { typicalPercent: 20, burstsPerDay: { min: 2, typical: 5, max: 10 }, incidentWeekPercent: 10 },
    interruptions: { perFocusHour: 1.3, recoveryMinutes: { min: 4, typical: 11, max: 25 }, sources: ["chat", "email", "meeting"] },
    stakeholders: ["Engineering", "Design", "Go-to-market", "Customers"],
    typicalWorkday: { start: "08:30", end: "17:30", workDays: [...ALL_WORK_DAYS] },
    seasonalPressures: ["Roadmap planning increases stakeholder meetings", "Launch ramps increase coordination and issue triage"],
  },
  {
    schemaVersion: 1, id: "product-designer", version: "1.0.0", role: "Product Designer", displayName: "Senior Product Designer",
    responsibilities: ["Frame user problems", "Develop interaction concepts", "Produce and validate prototypes", "Maintain design-system quality", "Support implementation review"],
    projects: ["Workflow redesign", "Design system evolution", "Usability study", "Launch polish"],
    appContexts: [
      context("design", "Figma", "SIMULATED — workflow prototype", "SIMULATED — component library"),
      context("browser", "Safari", "SIMULATED — research session", "SIMULATED — accessibility reference"),
      context("documents", "Notion Sandbox", "SIMULATED — research synthesis", "SIMULATED — design rationale"),
      context("chat", "Slack Sandbox", "SIMULATED — design critique", "SIMULATED — implementation support"),
      context("meetings", "Zoom Sandbox", "SIMULATED — usability session", "SIMULATED — product triad"),
    ],
    categoryWeights: categories([
      ["Planned analysis / project work", 34], ["Ad hoc stakeholder requests", 9], ["Recurring reporting", 3],
      ["Dashboard development / edits", 3], ["QA / data validation", 8], ["Debugging / issue investigation", 3],
      ["Documentation / requirement clarification", 12], ["Meetings / stakeholder syncs", 18], ["Admin / coordination", 7],
      ["Blocked / waiting / dependency delay", 3],
    ]),
    modeWeights: modes([["Deep work", 42], ["Reactive", 12], ["Collaborative", 25], ["Fragmented", 16], ["Blocked", 5]]),
    meetingBehavior: { weeklyMinutes: { min: 420, typical: 660, max: 960 }, recurringMeetings: ["Design critique", "Product triad", "Research readout"], doubleBookingPercent: 2 },
    deepWorkCadence: { preferredDays: [2, 3, 4], preferredStartHours: [9, 10, 13], blockMinutes: { min: 60, typical: 110, max: 180 } },
    reactiveLoad: { typicalPercent: 12, burstsPerDay: { min: 1, typical: 3, max: 7 }, incidentWeekPercent: 5 },
    interruptions: { perFocusHour: 0.7, recoveryMinutes: { min: 5, typical: 13, max: 28 }, sources: ["chat", "meeting", "email"] },
    stakeholders: ["Product", "Engineering", "Research participants", "Brand"],
    typicalWorkday: { start: "09:00", end: "17:30", workDays: [...ALL_WORK_DAYS] },
    seasonalPressures: ["Research rounds cluster interviews and synthesis", "Launch weeks add implementation QA and rapid revisions"],
  },
  {
    schemaVersion: 1, id: "customer-support-lead", version: "1.0.0", role: "Customer Support Lead", displayName: "Customer Support Lead",
    responsibilities: ["Coordinate queue health", "Resolve escalated cases", "Coach support specialists", "Identify recurring product issues", "Report service trends"],
    projects: ["Escalation reduction", "Support workflow improvement", "Knowledge-base refresh", "Service quality review"],
    appContexts: [
      context("support", "Support Sandbox", "SIMULATED — escalation queue", "SIMULATED — service review"),
      context("chat", "Slack Sandbox", "SIMULATED — escalation coordination", "SIMULATED — incident support"),
      context("spreadsheet", "Google Sheets Sandbox", "SIMULATED — queue metrics", "SIMULATED — staffing review"),
      context("documents", "Notion Sandbox", "SIMULATED — knowledge-base update", "SIMULATED — coaching plan"),
      context("meetings", "Zoom Sandbox", "SIMULATED — team coaching", "SIMULATED — product feedback"),
    ],
    categoryWeights: categories([
      ["Planned analysis / project work", 8], ["Ad hoc stakeholder requests", 35], ["Recurring reporting", 12],
      ["Dashboard development / edits", 4], ["SQL / data modeling / query work", 3], ["QA / data validation", 8],
      ["Debugging / issue investigation", 8], ["Documentation / requirement clarification", 5],
      ["Meetings / stakeholder syncs", 9], ["Admin / coordination", 6], ["Blocked / waiting / dependency delay", 2],
    ]),
    modeWeights: modes([["Deep work", 12], ["Reactive", 43], ["Collaborative", 19], ["Fragmented", 23], ["Blocked", 3]]),
    meetingBehavior: { weeklyMinutes: { min: 300, typical: 480, max: 720 }, recurringMeetings: ["Queue review", "Team coaching", "Product feedback sync"], doubleBookingPercent: 4 },
    deepWorkCadence: { preferredDays: [3, 5], preferredStartHours: [8, 15], blockMinutes: { min: 30, typical: 55, max: 100 } },
    reactiveLoad: { typicalPercent: 45, burstsPerDay: { min: 5, typical: 10, max: 20 }, incidentWeekPercent: 22 },
    interruptions: { perFocusHour: 2.2, recoveryMinutes: { min: 2, typical: 7, max: 18 }, sources: ["chat", "alert", "email"] },
    stakeholders: ["Customers", "Support team", "Product", "Engineering"],
    typicalWorkday: { start: "08:00", end: "16:30", workDays: [...ALL_WORK_DAYS] },
    seasonalPressures: ["Product launches increase case volume", "Service incidents produce immediate escalation spikes"],
  },
  {
    schemaVersion: 1, id: "sales-account-executive", version: "1.0.0", role: "Sales Account Executive", displayName: "Sales Account Executive",
    responsibilities: ["Develop qualified opportunities", "Run discovery and demonstrations", "Coordinate commercial follow-up", "Maintain pipeline accuracy", "Prepare account plans"],
    projects: ["Strategic account plan", "Quarter-end pipeline", "Evaluation process", "Territory development"],
    appContexts: [
      context("crm", "CRM Sandbox", "SIMULATED — account opportunity", "SIMULATED — pipeline update"),
      context("email", "Mail Sandbox", "SIMULATED — account follow-up", "SIMULATED — evaluation coordination"),
      context("meetings", "Zoom Sandbox", "SIMULATED — customer discovery", "SIMULATED — product demonstration"),
      context("documents", "Google Docs Sandbox", "SIMULATED — account plan", "SIMULATED — mutual action plan"),
      context("spreadsheet", "Google Sheets Sandbox", "SIMULATED — territory analysis", "SIMULATED — forecast review"),
    ],
    categoryWeights: categories([
      ["Planned analysis / project work", 12], ["Ad hoc stakeholder requests", 16], ["Recurring reporting", 9],
      ["Dashboard development / edits", 5], ["QA / data validation", 4], ["Debugging / issue investigation", 1],
      ["Documentation / requirement clarification", 8], ["Meetings / stakeholder syncs", 28], ["Admin / coordination", 15],
      ["Blocked / waiting / dependency delay", 2],
    ]),
    modeWeights: modes([["Deep work", 16], ["Reactive", 22], ["Collaborative", 38], ["Fragmented", 21], ["Blocked", 3]]),
    meetingBehavior: { weeklyMinutes: { min: 720, typical: 1020, max: 1440 }, recurringMeetings: ["Pipeline review", "Account strategy", "Customer discovery"], doubleBookingPercent: 5 },
    deepWorkCadence: { preferredDays: [1, 5], preferredStartHours: [8, 15], blockMinutes: { min: 30, typical: 60, max: 120 } },
    reactiveLoad: { typicalPercent: 23, burstsPerDay: { min: 3, typical: 6, max: 12 }, incidentWeekPercent: 3 },
    interruptions: { perFocusHour: 1.5, recoveryMinutes: { min: 3, typical: 9, max: 20 }, sources: ["email", "chat", "meeting"] },
    stakeholders: ["Prospects", "Customers", "Sales engineering", "Legal and finance"],
    typicalWorkday: { start: "08:30", end: "17:30", workDays: [...ALL_WORK_DAYS] },
    seasonalPressures: ["Quarter-end increases follow-up and pipeline administration", "Evaluation deadlines cluster customer meetings"],
  },
  {
    schemaVersion: 1, id: "marketing-manager", version: "1.0.0", role: "Marketing Manager", displayName: "Marketing Manager",
    responsibilities: ["Plan integrated campaigns", "Coordinate content production", "Analyze channel performance", "Manage launch communications", "Align marketing stakeholders"],
    projects: ["Product launch campaign", "Demand-generation program", "Content calendar", "Channel performance review"],
    appContexts: [
      context("marketing", "Campaign Sandbox", "SIMULATED — launch campaign", "SIMULATED — audience workflow"),
      context("analytics", "Analytics Sandbox", "SIMULATED — channel performance", "SIMULATED — campaign attribution"),
      context("design", "Figma", "SIMULATED — campaign creative", "SIMULATED — launch review"),
      context("spreadsheet", "Google Sheets Sandbox", "SIMULATED — content calendar", "SIMULATED — budget pacing"),
      context("chat", "Slack Sandbox", "SIMULATED — campaign coordination", "SIMULATED — launch channel"),
    ],
    categoryWeights: categories([
      ["Planned analysis / project work", 24], ["Ad hoc stakeholder requests", 12], ["Recurring reporting", 12],
      ["Dashboard development / edits", 8], ["SQL / data modeling / query work", 3], ["QA / data validation", 5],
      ["Debugging / issue investigation", 3], ["Documentation / requirement clarification", 8],
      ["Meetings / stakeholder syncs", 15], ["Admin / coordination", 8], ["Blocked / waiting / dependency delay", 2],
    ]),
    modeWeights: modes([["Deep work", 31], ["Reactive", 19], ["Collaborative", 24], ["Fragmented", 22], ["Blocked", 4]]),
    meetingBehavior: { weeklyMinutes: { min: 420, typical: 660, max: 960 }, recurringMeetings: ["Campaign review", "Content planning", "Launch readiness"], doubleBookingPercent: 3 },
    deepWorkCadence: { preferredDays: [2, 4], preferredStartHours: [9, 13], blockMinutes: { min: 45, typical: 90, max: 150 } },
    reactiveLoad: { typicalPercent: 20, burstsPerDay: { min: 2, typical: 5, max: 11 }, incidentWeekPercent: 6 },
    interruptions: { perFocusHour: 1.1, recoveryMinutes: { min: 4, typical: 11, max: 24 }, sources: ["chat", "email", "meeting"] },
    stakeholders: ["Product marketing", "Sales", "Creative", "Product"],
    typicalWorkday: { start: "09:00", end: "17:30", workDays: [...ALL_WORK_DAYS] },
    seasonalPressures: ["Launches ramp coordination and creative QA", "Quarter-end adds performance reporting and budget decisions"],
  },
  {
    schemaVersion: 1, id: "finance-analyst", version: "1.0.0", role: "Finance Analyst", displayName: "Senior Finance Analyst",
    responsibilities: ["Build operating forecasts", "Complete period-close analysis", "Validate financial controls", "Explain business variances", "Maintain reporting models"],
    projects: ["Quarterly forecast", "Month-end close", "Planning model", "Controls review"],
    appContexts: [
      context("spreadsheet", "Microsoft Excel", "SIMULATED — operating forecast", "SIMULATED — close workbook"),
      context("finance", "ERP Sandbox", "SIMULATED — ledger review", "SIMULATED — control validation"),
      context("bi", "Power BI", "SIMULATED — variance dashboard", "SIMULATED — financial reporting"),
      context("email", "Outlook Sandbox", "SIMULATED — forecast coordination", "SIMULATED — close questions"),
      context("documents", "SharePoint Sandbox", "SIMULATED — planning assumptions", "SIMULATED — control evidence"),
    ],
    categoryWeights: categories([
      ["Planned analysis / project work", 18], ["Ad hoc stakeholder requests", 8], ["Recurring reporting", 24],
      ["Dashboard development / edits", 6], ["SQL / data modeling / query work", 10], ["QA / data validation", 14],
      ["Debugging / issue investigation", 4], ["Documentation / requirement clarification", 4],
      ["Meetings / stakeholder syncs", 6], ["Admin / coordination", 4], ["Blocked / waiting / dependency delay", 2],
    ]),
    modeWeights: modes([["Deep work", 43], ["Reactive", 15], ["Collaborative", 11], ["Fragmented", 25], ["Blocked", 6]]),
    meetingBehavior: { weeklyMinutes: { min: 240, typical: 360, max: 600 }, recurringMeetings: ["Forecast review", "Close status", "Business-partner sync"], doubleBookingPercent: 1 },
    deepWorkCadence: { preferredDays: [2, 3, 4], preferredStartHours: [8, 9, 13], blockMinutes: { min: 60, typical: 120, max: 210 } },
    reactiveLoad: { typicalPercent: 14, burstsPerDay: { min: 1, typical: 3, max: 8 }, incidentWeekPercent: 5 },
    interruptions: { perFocusHour: 0.65, recoveryMinutes: { min: 5, typical: 14, max: 30 }, sources: ["email", "chat", "meeting"] },
    stakeholders: ["Business operations", "Accounting", "Executives", "Department leads"],
    typicalWorkday: { start: "08:30", end: "17:00", workDays: [...ALL_WORK_DAYS] },
    seasonalPressures: ["Month-end increases recurring and validation work", "Quarter-end forecasting creates a three-week ramp"],
  },
  {
    schemaVersion: 1, id: "operations-manager", version: "1.0.0", role: "Operations Manager", displayName: "Operations Manager",
    responsibilities: ["Maintain dependable operating workflows", "Coordinate incident response", "Improve service processes", "Monitor operating indicators", "Resolve cross-team dependencies"],
    projects: ["Process automation", "Operating review", "Service incident reduction", "Capacity planning"],
    appContexts: [
      context("operations", "Service Desk Sandbox", "SIMULATED — operations queue", "SIMULATED — incident workflow"),
      context("spreadsheet", "Google Sheets Sandbox", "SIMULATED — capacity plan", "SIMULATED — operating review"),
      context("bi", "Tableau", "SIMULATED — service dashboard", "SIMULATED — workflow metrics"),
      context("project", "Asana Sandbox", "SIMULATED — process improvement", "SIMULATED — dependency plan"),
      context("chat", "Slack Sandbox", "SIMULATED — operations coordination", "SIMULATED — incident channel"),
    ],
    categoryWeights: categories([
      ["Planned analysis / project work", 15], ["Ad hoc stakeholder requests", 22], ["Recurring reporting", 12],
      ["Dashboard development / edits", 7], ["SQL / data modeling / query work", 4], ["QA / data validation", 7],
      ["Debugging / issue investigation", 10], ["Documentation / requirement clarification", 5],
      ["Meetings / stakeholder syncs", 9], ["Admin / coordination", 7], ["Blocked / waiting / dependency delay", 2],
    ]),
    modeWeights: modes([["Deep work", 22], ["Reactive", 31], ["Collaborative", 20], ["Fragmented", 23], ["Blocked", 4]]),
    meetingBehavior: { weeklyMinutes: { min: 360, typical: 540, max: 840 }, recurringMeetings: ["Daily operations review", "Dependency sync", "Process improvement review"], doubleBookingPercent: 4 },
    deepWorkCadence: { preferredDays: [2, 4], preferredStartHours: [8, 14], blockMinutes: { min: 35, typical: 70, max: 130 } },
    reactiveLoad: { typicalPercent: 30, burstsPerDay: { min: 3, typical: 7, max: 15 }, incidentWeekPercent: 18 },
    interruptions: { perFocusHour: 1.7, recoveryMinutes: { min: 3, typical: 9, max: 22 }, sources: ["chat", "alert", "email", "meeting"] },
    stakeholders: ["Service owners", "Finance", "Customer support", "Vendors"],
    typicalWorkday: { start: "08:00", end: "16:30", workDays: [...ALL_WORK_DAYS] },
    seasonalPressures: ["Incidents cause correlated reactive spikes", "Planning cycles increase reporting and coordination"],
  },
  {
    schemaVersion: 1, id: "consultant", version: "1.0.0", role: "Consultant", displayName: "Senior Consultant",
    responsibilities: ["Structure ambiguous client questions", "Produce evidence-based analysis", "Facilitate working sessions", "Develop executive deliverables", "Coordinate parallel workstreams"],
    projects: ["Operating-model assessment", "Transformation roadmap", "Performance diagnostic", "Executive workshop"],
    appContexts: [
      context("presentation", "Microsoft PowerPoint", "SIMULATED — executive story", "SIMULATED — workshop deck"),
      context("spreadsheet", "Microsoft Excel", "SIMULATED — diagnostic model", "SIMULATED — scenario analysis"),
      context("meetings", "Teams Sandbox", "SIMULATED — client workshop", "SIMULATED — workstream review"),
      context("browser", "Microsoft Edge", "SIMULATED — industry research", "SIMULATED — benchmark review"),
      context("documents", "Microsoft Word", "SIMULATED — findings draft", "SIMULATED — recommendation memo"),
    ],
    categoryWeights: categories([
      ["Planned analysis / project work", 26], ["Ad hoc stakeholder requests", 13], ["Recurring reporting", 5],
      ["Dashboard development / edits", 6], ["SQL / data modeling / query work", 9], ["QA / data validation", 8],
      ["Debugging / issue investigation", 3], ["Documentation / requirement clarification", 12],
      ["Meetings / stakeholder syncs", 12], ["Admin / coordination", 5], ["Blocked / waiting / dependency delay", 1],
    ]),
    modeWeights: modes([["Deep work", 38], ["Reactive", 18], ["Collaborative", 22], ["Fragmented", 19], ["Blocked", 3]]),
    meetingBehavior: { weeklyMinutes: { min: 480, typical: 720, max: 1080 }, recurringMeetings: ["Client workstream", "Internal synthesis", "Executive checkpoint"], doubleBookingPercent: 3 },
    deepWorkCadence: { preferredDays: [2, 3, 5], preferredStartHours: [8, 9, 15], blockMinutes: { min: 50, typical: 100, max: 180 } },
    reactiveLoad: { typicalPercent: 18, burstsPerDay: { min: 2, typical: 4, max: 9 }, incidentWeekPercent: 4 },
    interruptions: { perFocusHour: 0.95, recoveryMinutes: { min: 4, typical: 12, max: 27 }, sources: ["email", "chat", "meeting"] },
    stakeholders: ["Client sponsors", "Client workstreams", "Consulting team", "Subject-matter experts"],
    typicalWorkday: { start: "08:30", end: "18:00", workDays: [...ALL_WORK_DAYS] },
    seasonalPressures: ["Executive deadlines create steep delivery ramps", "Workshop weeks cluster meetings before synthesis recovery"],
  },
];

export function getPersona(personaId: string): SimulationPersona | undefined {
  return PERSONA_CATALOG.find((persona) => persona.id === personaId);
}
